"""
explainer.py — Rule-based textual explanation generator for XAI Pneumonia Detection.

All explanations use cautious, non-absolute language (may indicate, patterns suggest,
possibly associated with) in compliance with medical AI best practices.
"""

from __future__ import annotations
from typing import Literal


def generate_explanation(
    prediction: Literal["PNEUMONIA", "NORMAL"],
    confidence: float,
    region_stats: dict,
) -> str:
    """
    Generate a human-readable, medically cautious explanation.

    Args:
        prediction:   "PNEUMONIA" or "NORMAL".
        confidence:   Model confidence in percent (0-100).
        region_stats: Output of gradcam.analyze_heatmap_regions().

    Returns:
        Multi-sentence explanation string.
    """
    upper = region_stats["upper_activation"]
    lower = region_stats["lower_activation"]
    peak = region_stats["peak_intensity"]
    spread = region_stats["activation_spread"]

    if prediction == "PNEUMONIA":
        return _pneumonia_explanation(confidence, upper, lower, peak, spread)
    return _normal_explanation(confidence, upper, lower, peak, spread)


# ── Pneumonia branch ──────────────────────────────────────────────────────────

def _pneumonia_explanation(
    confidence: float,
    upper: float,
    lower: float,
    peak: float,
    spread: float,
) -> str:
    sentences: list[str] = []

    # Confidence framing
    if confidence >= 90:
        sentences.append(
            "The model identified radiological patterns that may strongly suggest "
            "the presence of pneumonia-related changes in the lung tissue."
        )
    elif confidence >= 75:
        sentences.append(
            "The model detected patterns that possibly indicate pulmonary abnormalities "
            "consistent with pneumonia."
        )
    else:
        sentences.append(
            "The model found patterns that may weakly suggest pulmonary changes; "
            "results should be interpreted with caution given the lower confidence level."
        )

    # Region-specific observations
    dominant_region = "lower lung regions" if lower > upper else "upper lung regions"
    sentences.append(
        f"Activation was predominantly concentrated in the {dominant_region}, "
        "which may indicate localised opacity or consolidation patterns sometimes "
        "associated with infectious or inflammatory lung disease."
    )

    # Intensity and spread
    if peak > 0.8 and spread > 0.15:
        sentences.append(
            "The highlighted area covers a relatively broad region with high-intensity "
            "activation, possibly suggesting diffuse involvement of the lung parenchyma."
        )
    elif peak > 0.6:
        sentences.append(
            "Moderate-intensity activations were detected, which may point to focal "
            "opacity or early-stage consolidation patterns."
        )
    else:
        sentences.append(
            "Lower-intensity activations were observed, which could indicate subtle "
            "radiological changes that may warrant further clinical evaluation."
        )

    # Generic caution
    sentences.append(
        "These observations are generated by an AI model for educational purposes only "
        "and must not be used as a substitute for professional medical diagnosis."
    )

    return " ".join(sentences)


# ── Normal branch ─────────────────────────────────────────────────────────────

def _normal_explanation(
    confidence: float,
    upper: float,
    lower: float,
    peak: float,
    spread: float,
) -> str:
    sentences: list[str] = []

    if confidence >= 90:
        sentences.append(
            "The model found no significant patterns that would typically suggest "
            "pneumonia-related changes in the lung tissue."
        )
    elif confidence >= 75:
        sentences.append(
            "The model did not identify strong indicators of pneumonia; however, "
            "patterns were noted that may warrant routine clinical review."
        )
    else:
        sentences.append(
            "The model classified this image as normal with moderate confidence. "
            "Some ambiguous patterns were detected that may benefit from further evaluation."
        )

    if spread < 0.05:
        sentences.append(
            "Minimal regions of elevated activation were identified, which is "
            "consistent with a lung X-ray showing no marked pathological features."
        )
    else:
        sentences.append(
            "Some activation was noted in localised lung regions; while the model "
            "classified this as normal, these areas may represent anatomical variation "
            "or low-level findings that a clinician could further assess."
        )

    sentences.append(
        "These observations are generated by an AI model for educational purposes only "
        "and must not be used as a substitute for professional medical diagnosis."
    )

    return " ".join(sentences)